-- Supply dedicated fixture UUIDs via openvideo.test_host/test_viewer/test_moderator/test_video.
-- Transaction rollback preserves all real data, XP, notifications and rate counters.
begin;
do $$
declare host_user uuid:=current_setting('openvideo.test_host')::uuid;
 viewer_user uuid:=current_setting('openvideo.test_viewer')::uuid;
 moderator_user uuid:=current_setting('openvideo.test_moderator')::uuid;
 video uuid:=current_setting('openvideo.test_video')::uuid;
 c jsonb;e jsonb;r jsonb;xp_before bigint;xp_after bigint;mi jsonb;me uuid;ev jsonb;live uuid;vid uuid;i integer;
begin
 execute 'set local role service_role';
 mi=public.openvideo_mission_action(moderator_user,'create',jsonb_build_object('title','Rollback mission','requirements','Two approved video challenges','proof_kind','video','required_count',2,'xp',300,'deadline',now()+interval '1 day'));
 perform public.openvideo_mission_action(host_user,'accept',jsonb_build_object('id',mi->>'id'));
 select id into me from public.openvideo_mission_entries where mission_id=(mi->>'id')::uuid and user_id=host_user;
 c=public.openvideo_challenge_action(moderator_user,'create',jsonb_build_object('title','Rollback Live challenge','requirements','Test proof','proof_kind','live','scope','global','closes_at',now()+interval '1 day','duration_seconds',180));
 e=public.openvideo_challenge_action(host_user,'accept',jsonb_build_object('id',c->>'id'));
 r=public.openvideo_challenge_action(host_user,'list');
 if jsonb_array_length(r->'entries')<1 then raise exception 'Missing challenge entry';end if;
 begin perform public.openvideo_challenge_action(host_user,'submit',jsonb_build_object('id',e->>'id','proof_id',video));raise exception 'TEST FAILED: upload accepted as Live';
 exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 begin perform public.openvideo_challenge_action(host_user,'create',jsonb_build_object('title','Invalid'));raise exception 'TEST FAILED: nonmoderator issued challenge';
 exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 c=public.openvideo_challenge_action(moderator_user,'create',jsonb_build_object('title','Rollback video challenge','requirements','Test upload','proof_kind','video','scope','xp','closes_at',now()+interval '1 day','duration_seconds',180,'xp',500));
 e=public.openvideo_challenge_action(host_user,'accept',jsonb_build_object('id',c->>'id'));
 update public.videos set created_at=now(),visibility='public',status='published',safety_hidden=false where id=video;
 perform public.openvideo_challenge_action(host_user,'submit',jsonb_build_object('id',e->>'id','proof_id',video));
 xp_before=(public.openvideo_progress_action(host_user,'list')->>'xp')::bigint;
 perform public.openvideo_challenge_action(moderator_user,'review',jsonb_build_object('id',e->>'id','decision','completed','note','Transaction-only fixture'));
 xp_after=(public.openvideo_progress_action(host_user,'list')->>'xp')::bigint;
 if xp_after-xp_before<>500 then raise exception 'Wrong XP award';end if;
 perform openvideo_private.award_xp(host_user,'challenge',(e->>'id')::uuid,500);
 if (public.openvideo_progress_action(host_user,'list')->>'xp')::bigint<>xp_after then raise exception 'XP awarded twice';end if;
 select v.id into vid from public.videos v join public.channels ch on ch.id=v.channel_id where ch.owner_id=host_user and v.id<>video limit 1;
 if vid is null then raise exception 'Need two dedicated host video fixtures';end if;
 update public.videos set created_at=now(),visibility='public',status='published',safety_hidden=false where id=vid;
 c=public.openvideo_challenge_action(moderator_user,'create',jsonb_build_object('title','Second rollback video challenge','requirements','Test upload','proof_kind','video','scope','xp','closes_at',now()+interval '1 day','duration_seconds',180,'xp',100));
 e=public.openvideo_challenge_action(host_user,'accept',jsonb_build_object('id',c->>'id'));
 perform public.openvideo_challenge_action(host_user,'submit',jsonb_build_object('id',e->>'id','proof_id',vid));
 perform public.openvideo_challenge_action(moderator_user,'review',jsonb_build_object('id',e->>'id','decision','completed','note','Rollback test'));
 perform public.openvideo_mission_action(host_user,'complete',jsonb_build_object('id',me));
 perform public.openvideo_mission_action(host_user,'complete',jsonb_build_object('id',me));
 if (public.openvideo_progress_action(host_user,'list')->>'xp')::bigint<>xp_after+400 then raise exception 'Mission award incorrect or duplicated';end if;
 if(select count(*) from public.openvideo_mission_evidence where mission_entry=me)<>2 then raise exception 'Missing mission evidence';end if;
 perform public.openvideo_mission_action(host_user,'list');
 r=public.openvideo_request_action(viewer_user,'create',jsonb_build_object('title','Rollback request','country','Test country','city','Test city','deadline',now()+interval '1 hour'));
 perform public.openvideo_request_action(host_user,'accept',jsonb_build_object('id',r->>'id'));
 select id into live from public.live_sessions where owner_id=host_user and state='ended' order by created_at desc limit 1;
 update public.live_sessions set started_at=now(),state='live',heartbeat_at=now(),country='Test country',city='Test city',access='public',safety_hidden=false where id=live;
 perform public.openvideo_request_action(host_user,'start',jsonb_build_object('id',r->>'id','live_id',live));
 ev=public.openvideo_event_action(host_user,'create',jsonb_build_object('title','Rollback event','topic','Testing'));
 perform public.openvideo_event_action(host_user,'join',jsonb_build_object('id',ev->>'id','live_id',live));
 if not exists(select 1 from public.openvideo_event_members where event_id=(ev->>'id')::uuid and live_id=live) then raise exception 'Event join failed';end if;
 begin perform public.openvideo_event_action(viewer_user,'join',jsonb_build_object('id',ev->>'id','live_id',live));raise exception 'TEST FAILED: another user joined my Live';exception when others then if sqlerrm like 'TEST FAILED%' then raise;end if;end;
 perform public.openvideo_event_action(host_user,'list');
 update public.live_sessions set state='ended',ended_at=now() where id=live;
 perform public.openvideo_request_action(host_user,'complete',jsonb_build_object('id',r->>'id'));
 if(select status from public.openvideo_requests where id=(r->>'id')::uuid)<>'completed' then raise exception 'Request not completed';end if;
 perform openvideo_private.process_deadlines();
 if has_function_privilege('authenticated','public.openvideo_challenge_action(uuid,text,jsonb)','execute') or has_table_privilege('authenticated','public.openvideo_xp_ledger','insert') then raise exception 'Privileged API exposed';end if;
end $$;
rollback;
