-- OpenVideo V6.6 — Qualified + repeat-resistant views
-- A public view counts only after qualified watch time.
-- The same browser/account can count a given video only once per 24 hours.
-- The creator's own signed-in views never count.

create table if not exists public.video_view_events (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.videos(id) on delete cascade,
  viewer_key text not null,
  viewer_user_id uuid null,
  viewed_at timestamptz not null default now()
);

create index if not exists video_view_events_lookup_idx
on public.video_view_events (video_id, viewer_key, viewed_at desc);

alter table public.video_view_events enable row level security;

-- No direct browser table writes are needed; the RPC below is SECURITY DEFINER.

create or replace function public.record_video_view_v66(
  p_video_id uuid,
  p_viewer_key text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  current_count bigint;
  effective_key text;
  current_user_id uuid;
begin
  current_user_id := auth.uid();

  -- Signed-in accounts use a stable account-based key.
  -- Signed-out viewers use the persistent browser key sent by OpenVideo.
  effective_key := case
    when current_user_id is not null then 'user:' || current_user_id::text
    else 'browser:' || coalesce(nullif(trim(p_viewer_key),''),'missing')
  end;

  -- Creator's own signed-in play never counts.
  if exists (
    select 1
    from public.videos v
    join public.channels c on c.id = v.channel_id
    where v.id = p_video_id
      and c.owner_id = current_user_id
  ) then
    select coalesce(v.view_count,0) into current_count
    from public.videos v
    where v.id = p_video_id;
    return coalesce(current_count,0);
  end if;

  -- Only public + published videos are eligible.
  if not exists (
    select 1
    from public.videos v
    where v.id = p_video_id
      and v.visibility = 'public'
      and v.status = 'published'
  ) then
    select coalesce(v.view_count,0) into current_count
    from public.videos v
    where v.id = p_video_id;
    return coalesce(current_count,0);
  end if;

  -- Same viewer + same video: max 1 counted view per rolling 24 hours.
  if exists (
    select 1
    from public.video_view_events e
    where e.video_id = p_video_id
      and e.viewer_key = effective_key
      and e.viewed_at >= now() - interval '24 hours'
  ) then
    select coalesce(v.view_count,0) into current_count
    from public.videos v
    where v.id = p_video_id;
    return coalesce(current_count,0);
  end if;

  insert into public.video_view_events(video_id, viewer_key, viewer_user_id)
  values (p_video_id, effective_key, current_user_id);

  update public.videos v
  set view_count = coalesce(v.view_count,0) + 1
  where v.id = p_video_id
  returning v.view_count into current_count;

  return coalesce(current_count,0);
end;
$$;

grant execute on function public.record_video_view_v66(uuid,text) to anon, authenticated;

select 'OpenVideo V6.6 qualified + repeat-resistant views ready!' as status;
