const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const users=JSON.parse(fs.readFileSync(process.env.OPENVIDEO_TEST_USERS_PATH));const root=path.resolve(__dirname,'..'),output=path.resolve(root,'../../../../outputs');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(4175,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||undefined,headless:true});let host,viewer,requestId,eventId;
 const api=(p,module,action,data={})=>p.evaluate(({module,action,data})=>OpenVideoCommunity.api(module,action,data),{module,action,data});
 try{const errors=[],pages=[];for(const u of users){const ctx=await browser.newContext();const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4175');await p.waitForFunction(()=>!!window.OpenVideoCommunity);assert(await p.evaluate(async u=>{const {data,error}=await sb.auth.signInWithPassword(u);authUser=data.user;await ensureChannel();return !error;},{email:u.email,password:u.password}));pages.push(p);}[host,viewer]=pages;
  for(const module of ['challenge','progress','request','mission','event']){const r=await api(host,module,'list');assert(r&&typeof r==='object');}console.log('PASS: all five authenticated community modules load');
  const denied=await host.evaluate(async()=>{try{await OpenVideoCommunity.api('challenge','create',{title:'Unprivileged'});return false;}catch{return true;}});assert(denied);console.log('PASS: ordinary account cannot issue platform challenges');
  await host.evaluate(()=>go('requests'));await host.fill('#requestCountry','Test country');await host.fill('#requestCity','Test city');await host.click('#requestAlertsOn');await host.waitForFunction(()=>document.getElementById('requestAlertStatus').textContent.includes('Test country'));
  await viewer.evaluate(()=>go('requests'));await viewer.locator('#view-requests summary').click();await viewer.fill('#requestForm [name=title]','Automated request fixture');await viewer.fill('#requestForm [name=country]','Test country');await viewer.fill('#requestForm [name=city]','Test city');await viewer.fill('#requestForm [name=deadline]',new Date(Date.now()+3600000).toISOString().slice(0,16));await viewer.locator('#requestForm button').click();await viewer.waitForFunction(()=>document.getElementById('requestList').textContent.includes('Automated request fixture'));
  requestId=(await api(viewer,'request','list')).requests.find(r=>r.title==='Automated request fixture'&&r.status==='requested').id;
  await host.click('#requestRefresh');await host.locator(`[data-request-action="accept"][data-id="${requestId}"]`).click();await host.waitForFunction(()=>document.getElementById('requestList').textContent.includes('accepted'));
  await viewer.evaluate(()=>go('notifications'));await viewer.click('#notificationRefresh');await viewer.waitForFunction(()=>document.getElementById('notificationList').textContent.includes('Request accepted'));
  await host.evaluate(()=>go('notifications'));await host.click('#notificationRefresh');await host.waitForFunction(()=>document.getElementById('notificationList').textContent.includes('New request in your chosen area'));
  console.log('PASS: real request creation, area opt-in notification, voluntary acceptance and requester inbox');
  await api(host,'request','cancel',{id:requestId});assert.equal((await api(viewer,'request','list')).requests.find(r=>r.id===requestId).status,'cancelled');requestId=null;await api(host,'request','alerts',{enabled:false});
  await host.evaluate(()=>go('multiview'));await host.locator('#view-multiview summary').click();await host.fill('#eventForm [name=title]','Automated event fixture');await host.fill('#eventForm [name=topic]','Verification');await host.locator('#eventForm button').click();await host.waitForFunction(()=>document.getElementById('eventList').textContent.includes('Automated event fixture'));eventId=(await api(host,'event','list')).events.find(e=>e.title==='Automated event fixture').id;
  const deniedClose=await viewer.evaluate(async id=>{try{await OpenVideoCommunity.api('event','close',{id});return false;}catch{return true;}},eventId);assert(deniedClose);await host.locator(`[data-event-close="${eventId}"]`).click();await host.waitForFunction(()=>!document.getElementById('eventList').textContent.includes('Automated event fixture'));eventId=null;console.log('PASS: event creation, ownership protection and close');
  for(const route of ['live','challenges','progress','requests','live-map','missions','multiview','notifications','safety']){await host.evaluate(r=>go(r),route);await host.locator('#view-'+route).waitFor({state:'visible'});await host.waitForTimeout(250);}
  await host.setViewportSize({width:390,height:844});for(const route of ['live','challenges','progress','requests','live-map','missions','multiview']){await host.evaluate(r=>go(r),route);assert(await host.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow on '+route);}
  await host.evaluate(()=>go('live'));await host.screenshot({path:path.join(output,'community-live-mobile.png'),fullPage:true});assert.equal(errors.length,0,errors.join('; '));console.log('PASS: community navigation, mobile layout and no browser exceptions');
 }finally{if(host){if(requestId)await api(host,'request','cancel',{id:requestId}).catch(()=>{});if(eventId)await api(host,'event','close',{id:eventId}).catch(()=>{});await api(host,'request','alerts',{enabled:false}).catch(()=>{});}await browser.close();server.close();}
})().catch(e=>{console.error('FAIL:',e.message);server.close();process.exitCode=1;});
