import test from 'node:test';import assert from 'node:assert/strict';
let handler;globalThis.Deno={env:{get:k=>k==='SUPABASE_URL'?'https://db.test':'secret'},serve:f=>handler=f};
await import('../supabase/functions/openvideo-safety/index.ts');
const uid='11111111-1111-4111-8111-111111111111';
function mock(routes={},valid=true){const calls=[];globalThis.fetch=async(url,o={})=>{const p=new URL(url).pathname;calls.push({p,method:o.method||'GET',body:o.body});if(p==='/auth/v1/user')return Response.json(valid?{id:uid}:{error:'bad'},{status:valid?200:401});if(p in routes)return Response.json(routes[p]);throw Error('Unexpected database request');};return calls;}
async function request(action,body={},auth=true){const r=await handler(new Request('https://edge.test',{method:'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer token'}:{})},body:JSON.stringify({action,...body})}));return {status:r.status,body:await r.json()};}
test('safety requires valid non-anonymous authentication',async()=>{mock();assert.equal((await request('queue',{},false)).status,401);const calls=mock({},false);assert.equal((await request('queue')).status,401);assert.equal(calls.length,1);});
test('ordinary account cannot inspect queue or moderate',async()=>{for(const action of ['queue','review','review-target']){const calls=mock({'/rest/v1/openvideo_moderators':[]});assert.equal((await request(action)).status,403);assert.ok(calls.every(c=>c.method==='GET'));}});
test('report reasons and target identifiers are validated before writing',async()=>{const calls=mock();assert.equal((await request('report',{reason:'bad'})).status,400);assert.equal((await request('report',{reason:'spam',kind:'video',targetId:'not-uuid'})).status,400);assert.ok(calls.every(c=>c.method==='GET'));});
test('server rate limiter rejects excess reports',async()=>{mock({'/rest/v1/videos':[{id:uid}],'/rest/v1/rpc/openvideo_consume_limit':false});assert.equal((await request('report',{reason:'spam',kind:'video',targetId:uid})).status,429);});
test('clients cannot choose report status or reporter identity',async()=>{const calls=mock({'/rest/v1/videos':[{id:uid}],'/rest/v1/rpc/openvideo_consume_limit':true,'/rest/v1/reports':[]});await request('report',{reason:'spam',kind:'video',targetId:uid,reporter_id:'attacker',status:'resolved'});const sent=JSON.parse(calls.find(c=>c.p==='/rest/v1/reports'&&c.method==='POST').body);assert.equal(sent.reporter_id,uid);assert.equal(sent.status,'open');});
test('self blocking is rejected',async()=>{mock();assert.equal((await request('block',{userId:uid,blocked:true})).status,400);});
